image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  CONTAINER_IMAGE: registry.klocapps.com/shopify/shopify-kloc-raffle:$CI_COMMIT_SHORT_SHA
  STAGING_DOMAIN: staging-raffle.klocapps.com
  PRODUCTION_DOMAIN: raffle.klocapps.com
  
stages:
  - build
  - staging
  - production

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_LOGIN registry.klocapps.com
  
.ssh_template: &ssh_definition
   - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
   - eval $(ssh-agent -s)
   
.ssh_and_known_host_modification_template: &ssh_and_known_host_modification_definition
   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh
   - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
   
.only-default: &only-default
  only:
    - master

build:
  stage: build
  script:
   - docker pull registry.klocapps.com/shopify/shopify-kloc-raffle || true
   - docker build --cache-from registry.klocapps.com/shopify/shopify-kloc-raffle --tag $CONTAINER_IMAGE .
   - docker push $CONTAINER_IMAGE
  <<: *only-default

deploy_staging:
  stage: staging
  variables:
    DOMAIN: $STAGING_DOMAIN
  script:
   - *ssh_definition
   - echo "$S_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
   - *ssh_and_known_host_modification_definition
   - ssh kloc-admin@174.138.123.31 "sudo echo "TAG=$CI_COMMIT_SHORT_SHA"$'\n'"RAILS_MAX_THREADS=$RAILS_MAX_THREADS"$'\n'"RAFFLE_DATABASE_NAME=$RAFFLE_DATABASE_NAME"$'\n'"RAFFLE_DATABASE_USERNAME=$RAFFLE_DATABASE_USERNAME"$'\n'"RAFFLE_DATABASE_PASSWORD=$RAFFLE_DATABASE_PASSWORD"$'\n'"HOST=$S_HOST"$'\n'"DB_PORT=$DB_PORT"$'\n'"SHOPIFY_API_KEY=$S_SHOPIFY_API_KEY"$'\n'"SHOPIFY_API_SECRET=$S_SHOPIFY_API_SECRET"$'\n'"URL=$URL"$'\n'"ADMIN_NAME=$ADMIN_NAME"$'\n'"ADMIN_PASSWORD=$ADMIN_PASSWORD"$'\n'"SIDEKIQ_URL=$SIDEKIQ_URL"$'\n'"REDIS_USERNAME=$REDIS_USERNAME"$'\n'"REDIS_PASSWORD=$REDIS_PASSWORD"> .env && sudo docker-compose config && sudo docker-compose up -d && sudo docker-compose run rails bundle exec rake db:create && sudo docker-compose run rails bundle exec rake db:migrate "
  environment:
    name: staging
    url: https://$DOMAIN
  <<: *only-default


.deploy_production:
  stage: production
  variables:
    DOMAIN: $PRODUCTION_DOMAIN
  script:
   - *ssh_definition
   - echo "$P_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
   - *ssh_and_known_host_modification_definition
   - ssh kloc-admin@68.183.247.108 "sudo env "TAG=$CI_COMMIT_SHORT_SHA" "P_MONGOURI=$P_MONGOURI" "G_MSG91=$G_MSG91" "P_APP_URI=$P_APP_URI" "P_APP_URL=$P_APP_URL" "G_DATABASE_NAME=$G_DATABASE_NAME" "P_SHOPIFY_API_KEY=$P_SHOPIFY_API_KEY" "P_SHOPIFY_SHARED_SECRET=$P_SHOPIFY_SHARED_SECRET" "G_APP_SCOPE=$G_APP_SCOPE" "G_APP_NAME=$G_APP_NAME" "G_PERSMS=$G_PERSMS" docker stack deploy --with-registry-auth -c docker-compose.yml loginotp" 
  environment:
    name: prodution
    url: https://$DOMAIN
  when: manual
  

.rollback_production:
  stage: production
  script:
   - *ssh_definition
   - echo "$P_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
   - *ssh_and_known_host_modification_definition
   - ssh kloc-admin@68.183.247.108 "sudo docker service rollback loginotp_apdp"
  environment:
    name: prodution
  when: manual

