image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  CONTAINER_IMAGE: registry.klocapps.com/shopify/shopify-kloc-raffle:$CI_COMMIT_SHORT_SHA
  STAGING_DOMAIN: staging-raffle.klocapps.com
  PRODUCTION_DOMAIN: raffle.klocapps.com
  
stages:
  - build
  - staging
  - production

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_LOGIN registry.klocapps.com
  
.ssh_template: &ssh_definition
   - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
   - eval $(ssh-agent -s)
   
.ssh_and_known_host_modification_template: &ssh_and_known_host_modification_definition
   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh
   - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
   
.only-default: &only-default
  only:
    - master

build:
  stage: build
  script:
   - docker pull registry.klocapps.com/shopify/shopify-kloc-raffle:971f9517 || true
   - docker build --cache-from registry.klocapps.com/shopify/shopify-kloc-raffle:971f9517 --tag $CONTAINER_IMAGE .
   - docker push $CONTAINER_IMAGE
  <<: *only-default

deploy_staging:
  stage: staging
  variables:
    DOMAIN: $STAGING_DOMAIN
  script:
   - *ssh_definition
   - echo "$S_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
   - *ssh_and_known_host_modification_definition
   - ssh kloc-admin@174.138.123.31 "cd shopify-kloc-raffle/ && git pull"
   - ssh kloc-admin@174.138.123.31 "sudo echo "TAG=$CI_COMMIT_SHORT_SHA"$'\n'"RAILS_MAX_THREADS=$S_RAILS_MAX_THREADS"$'\n'"RAFFLE_DATABASE_NAME=$RAFFLE_DATABASE_NAME"$'\n'"RAFFLE_DATABASE_USERNAME=$RAFFLE_DATABASE_USERNAME"$'\n'"RAFFLE_DATABASE_PASSWORD=$RAFFLE_DATABASE_PASSWORD"$'\n'"HOST=$S_HOST"$'\n'"DB_PORT=$DB_PORT"$'\n'"SHOPIFY_API_KEY=$S_SHOPIFY_API_KEY"$'\n'"SHOPIFY_API_SECRET=$S_SHOPIFY_API_SECRET"$'\n'"URL=$S_URL"$'\n'"SIDEKIQ_USERNAME=$SIDEKIQ_USERNAME"$'\n'"SIDEKIQ_PASSWORD=$SIDEKIQ_PASSWORD"$'\n'"REDIS_URL=$S_REDIS_URL"$'\n'"KEY=$S_ENCRYPT_AND_DECRYPT_KEY"$'\n'"EMAIL_API=$SENDGRID_EMAIL"$'\n'"EMAIL_PWD=$SENDGRID_PASSWORD"$'\n'"EMAIL_SMTP=$SENDGRID_SMTP"$'\n'"DOMAIN=$S_DOMAIN"$'\n'"OTP_DURATION=$OTP_DURATION"$'\n'"EMAIL=$S_EMAIL"> .env && sudo docker-compose config && sudo docker-compose up -d && sudo docker-compose run rails bundle exec rake db:create && sudo docker-compose run rails bundle exec rake db:migrate "
  environment:
    name: staging
    url: https://$DOMAIN
  <<: *only-default


deploy_production:
  stage: production
  variables:
    DOMAIN: $PRODUCTION_DOMAIN
  script:
   - *ssh_definition
   - echo "$P_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
   - *ssh_and_known_host_modification_definition
   - ssh ubuntu@54.215.115.70 "sudo env "TAG=$CI_COMMIT_SHORT_SHA" "RAILS_MAX_THREADS=$P_RAILS_MAX_THREADS" "RAFFLE_DATABASE_NAME=$P_RAFFLE_DATABASE_NAME" "RAFFLE_DATABASE_USERNAME=$P_RAFFLE_DATABASE_USERNAME" "RAFFLE_DATABASE_PASSWORD=$P_RAFFLE_DATABASE_PASSWORD" "HOST=$P_HOST" "SHOPIFY_API_KEY=$P_SHOPIFY_API_KEY" "SHOPIFY_API_SECRET=$P_SHOPIFY_API_SECRET" "URL=$P_URL" "SIDEKIQ_USERNAME=$SIDEKIQ_USERNAME" "SIDEKIQ_PASSWORD=$SIDEKIQ_PASSWORD" "DB_PORT=$DB_PORT" "REDIS_URL=$P_REDIS_URL" "KEY=$P_ENCRYPT_AND_DECRYPT_KEY" "EMAIL_API=$AWS_API_KEY" "EMAIL_PWD=$AWS_SECRET_KEY" "EMAIL_SMTP=$AWS_SMTP" "EMAIL=$P_EMAIL" "DOMAIN=$P_DOMAIN" "OTP_DURATION=$OTP_DURATION" docker stack deploy --with-registry-auth -c docker-compose.yml raffle" 
  environment:
    name: prodution
    url: https://$DOMAIN
  when: manual
  

.rollback_production:
  stage: production
  script:
   - *ssh_definition
   - echo "$P_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
   - *ssh_and_known_host_modification_definition
   - ssh ubuntu@54.215.115.70 "sudo docker service rollback loginotp_apdp"
  environment:
    name: prodution
  when: manual

