
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") %>
  database: <%= ENV.fetch("RAFFLE_DATABASE_NAME") %>
  username: <%= ENV.fetch("RAFFLE_DATABASE_USERNAME") %>
  password: <%= ENV.fetch("RAFFLE_DATABASE_PASSWORD") %>
  port: <%= ENV.fetch("DB_PORT") %>
  host: <%= ENV.fetch("HOST") %>
  
development:
   <<: *default

test:
   <<: *default

production:
   <<: *default